name: Lint

on:
  pull_request:
    branches: [main]

  push:
    branches: [main]


jobs:
  lint:
    runs-on: ubuntu-latest
               - name: Checkout
                 uses: actions/checkout@v3
               - name: Install dependencies
                 uses: npm ci
               - name: Lint
                 uses: run npm run lint
